services:
  - type: web
    name: weather-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    pythonVersion: 3.11.12
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_actual_bot_token_here
